export const countryNames = [
  { en: "Afghanistan  ", sv: "Afghanistan" },
  { en: "Albania  ", sv: "Albanien" },
  { en: "Algeria  ", sv: "Algeriet" },
  { en: "Andorra  ", sv: "Andorra" },
  { en: "Angola  ", sv: "Angola" },
  { en: "Antigua and Barbuda ", sv: "Antigua och Barbuda" },
  { en: "Argentina  ", sv: "Argentina" },
  { en: "Armenia  ", sv: "Armenien" },
  { en: "Australia  ", sv: "Australien" },
  { en: "Austria  ", sv: "Österrike" },
  { en: "Azerbaijan  ", sv: "Azerbajdzjan" },
  { en: "Bahamas  ", sv: "Bahamas" },
  { en: "Bahrain  ", sv: "Bahrain" },
  { en: "Bangladesh  ", sv: "Bangladesh" },
  { en: "Barbados  ", sv: "Barbados" },
  { en: "Belarus  ", sv: "Vitryssland" },
  { en: "Belgium  ", sv: "Belgien" },
  { en: "Belize  ", sv: "Belize" },
  { en: "Benin  ", sv: "Benin" },
  { en: "Bhutan  ", sv: "Bhutan" },
  { en: "Bolivia  ", sv: "Bolivia" },
  { en: "Bosnia and Herzegovina ", sv: "Bosnien och Hercegovina" },
  { en: "Botswana  ", sv: "Botswana" },
  { en: "Brazil  ", sv: "Brasilien" },
  { en: "Brunei  ", sv: "Brunei" },
  { en: "Bulgaria  ", sv: "Bulgarien" },
  { en: "Burkina Faso ", sv: "Burkina Faso" },
  { en: "Burundi  ", sv: "Burundi" },
  { en: "Cambodia  ", sv: "Kambodja" },
  { en: "Cameroon  ", sv: "Kamerun" },
  { en: "Canada  ", sv: "Kanada" },
  { en: "Cape Verde ", sv: "Kap Verde" },
  { en: "Central African Republic ", sv: "Centralafrikanska republiken" },
  { en: "Chad  ", sv: "Tchad" },
  { en: "Chile  ", sv: "Chile" },
  { en: "China  ", sv: "Kina" },
  { en: "Colombia  ", sv: "Colombia" },
  { en: "Comoros  ", sv: "Komorerna" },
  { en: "Costa Rica ", sv: "Costa Rica" },
  { en: "Côte d’Ivoire  ", sv: "Elfenbenskusten" },
  { en: "Croatia  ", sv: "Kroatien" },
  { en: "Cuba  ", sv: "Kuba" },
  { en: "Cyprus  ", sv: "Cypern" },
  { en: "Czech Republic ", sv: "Tjeckien" },
  { en: "Democratic Republic of the Congo ", sv: "Demokratiska republiken Kongo" },
  { en: "Denmark  ", sv: "Danmark" },
  { en: "Djibouti  ", sv: "Djibouti" },
  { en: "Dominica  ", sv: "Dominica" },
  { en: "Dominican Republic ", sv: "Dominikanska republiken" },
  { en: "East Timor ", sv: "Östtimor" },
  { en: "Ecuador  ", sv: "Ecuador" },
  { en: "Egypt  ", sv: "Egypten" },
  { en: "El Salvador ", sv: "El Salvador" },
  { en: "Equatorial Guinea ", sv: "Ekvatorialguinea" },
  { en: "Eritrea  ", sv: "Eritrea" },
  { en: "Estonia  ", sv: "Estland" },
  { en: "Ethiopia  ", sv: "Etiopien" },
  { en: "Fiji  ", sv: "Fiji" },
  { en: "Finland  ", sv: "Finland" },
  { en: "France  ", sv: "Frankrike" },
  { en: "Gabon  ", sv: "Gabon" },
  { en: "Gambia  ", sv: "Gambia" },
  { en: "Georgia  ", sv: "Georgien" },
  { en: "Germany  ", sv: "Tyskland" },
  { en: "Ghana  ", sv: "Ghana" },
  { en: "Greece  ", sv: "Grekland" },
  { en: "Grenada  ", sv: "Grenada" },
  { en: "Guatemala  ", sv: "Guatemala" },
  { en: "Guinea  ", sv: "Guinea" },
  { en: "Guinea Bissau  ", sv: "Guinea Bissau" },
  { en: "Guyana  ", sv: "Guyana" },
  { en: "Haiti  ", sv: "Haiti" },
  { en: "Honduras  ", sv: "Honduras" },
  { en: "Hungary  ", sv: "Ungern" },
  { en: "Iceland  ", sv: "Island" },
  { en: "India  ", sv: "Indien" },
  { en: "Indonesia  ", sv: "Indonesien" },
  { en: "Iran  ", sv: "Iran" },
  { en: "Iraq  ", sv: "Irak" },
  { en: "Ireland  ", sv: "Irland" },
  { en: "Israel  ", sv: "Israel" },
  { en: "Italy  ", sv: "Italien" },
  { en: "Jamaica  ", sv: "Jamaica" },
  { en: "Japan  ", sv: "Japan" },
  { en: "Jordan  ", sv: "Jordan" },
  { en: "Kazakhstan  ", sv: "Kazakstan" },
  { en: "Kenya  ", sv: "Kenya" },
  { en: "Kiribati  ", sv: "Kiribati" },
  { en: "Kuwait  ", sv: "Kuwait" },
  { en: "Kyrgyzstan  ", sv: "Kirgizistan" },
  { en: "Laos  ", sv: "Laos" },
  { en: "Latvia  ", sv: "Lettland" },
  { en: "Lebanon  ", sv: "Libanon" },
  { en: "Lesotho  ", sv: "Lesotho" },
  { en: "Liberia  ", sv: "Liberia" },
  { en: "Libya  ", sv: "Libyen" },
  { en: "Liechtenstein  ", sv: "Liechtenstein" },
  { en: "Lithuania  ", sv: "Litauen" },
  { en: "Luxembourg  ", sv: "Luxemburg" },
  { en: "Madagascar  ", sv: "Madagaskar" },
  { en: "Malawi  ", sv: "Malawi" },
  { en: "Malaysia  ", sv: "Malaysia" },
  { en: "Maldives  ", sv: "Maldiverna" },
  { en: "Mali  ", sv: "Mali" },
  { en: "Malta  ", sv: "Malta" },
  { en: "Marshall Islands ", sv: "arna" },
  { en: "Mauritania  ", sv: "Mauretanien" },
  { en: "Mauritius  ", sv: "Mauritius" },
  { en: "Mexico  ", sv: "Mexiko" },
  { en: "Micronesia  ", sv: "Mikronesien" },
  { en: "Moldova  ", sv: "Moldavien" },
  { en: "Monaco  ", sv: "Monaco" },
  { en: "Mongolia  ", sv: "Mongoliet" },
  { en: "Montenegro  ", sv: "Montenegro" },
  { en: "Morocco  ", sv: "Marocko" },
  { en: "Mozambique  ", sv: "Moçambique" },
  { en: "Myanmar  ", sv: "Burma" },
  { en: "Namibia  ", sv: "Namibia" },
  { en: "Nauru  ", sv: "Nauru" },
  { en: "Nepal  ", sv: "Nepal" },
  { en: "Netherlands  ", sv: "Nederländerna" },
  { en: "New Zealand ", sv: "Nya Zeeland" },
  { en: "Nicaragua  ", sv: "Nicaragua" },
  { en: "Niger  ", sv: "Niger" },
  { en: "Nigeria  ", sv: "Nigeria" },
  { en: "North Korea ", sv: "Nordkorea" },
  { en: "Norway  ", sv: "Norge" },
  { en: "Oman  ", sv: "Oman" },
  { en: "Pakistan  ", sv: "Pakistan" },
  { en: "Palau  ", sv: "Palau" },
  { en: "Panama  ", sv: "Panama" },
  { en: "Papua New Guinea ", sv: "Papua Nya Guinea" },
  { en: "Paraguay  ", sv: "Paraguay" },
  { en: "Peru  ", sv: "Peru" },
  { en: "Philippines  ", sv: "Filippinerna" },
  { en: "Poland  ", sv: "Polen" },
  { en: "Portugal  ", sv: "Portugal" },
  { en: "Qatar  ", sv: "Qatar" },
  { en: "Republic of the Congo ", sv: "Republiken Kongo" },
  { en: "Republic of Macedonia ", sv: "Makedonien" },
  { en: "Romania  ", sv: "Rumänien" },
  { en: "Russia  ", sv: "Ryssland" },
  { en: "Rwanda  ", sv: "Rwanda" },
  { en: "Saint Kitts and Nevis ", sv: "Saint Kitts och Nevis" },
  { en: "Saint Lucia ", sv: "Saint Lucia" },
  { en: "Saint Vincent and the Grenadines ", sv: "Saint Vincent och Grenadinerna" },
  { en: "Samoa  ", sv: "Samoa" },
  { en: "San Marino ", sv: "San Marino" },
  { en: "Sao Tome and Principe ", sv: "São Tomé och Príncipe" },
  { en: "Saudi Arabia ", sv: "Saudiarabien" },
  { en: "Senegal  ", sv: "Senegal" },
  { en: "Serbia  ", sv: "Serbien" },
  { en: "Seychelles  ", sv: "Seychellerna" },
  { en: "Sierra Leone ", sv: "Sierra Leone" },
  { en: "Singapore  ", sv: "Singapore" },
  { en: "Slovakia  ", sv: "Slovakien" },
  { en: "Slovenia  ", sv: "Slovenien" },
  { en: "Solomon Islands ", sv: "Salomonöarna" },
  { en: "Somalia  ", sv: "Somalia" },
  { en: "South Africa ", sv: "Sydafrika" },
  { en: "South Korea ", sv: "Sydkorea" },
  { en: "South Sudan ", sv: "Sydsudan" },
  { en: "Spain  ", sv: "Spanien" },
  { en: "Sri Lanka ", sv: "Sri Lanka" },
  { en: "Sudan  ", sv: "Sudan" },
  { en: "Suriname  ", sv: "Surinam" },
  { en: "Swaziland  ", sv: "Swaziland" },
  { en: "Sweden  ", sv: "Sverige" },
  { en: "Switzerland  ", sv: "Schweiz" },
  { en: "Syria  ", sv: "Syrien" },
  { en: "Tajikistan  ", sv: "Tadzjikistan" },
  { en: "Tanzania  ", sv: "Tanzania" },
  { en: "Thailand  ", sv: "Thailand" },
  { en: "Togo  ", sv: "Togo" },
  { en: "Tonga  ", sv: "Tonga" },
  { en: "Trinidad and Tobago ", sv: "Trinidad och Tobago" },
  { en: "Tunisia  ", sv: "Tunisien" },
  { en: "Turkey  ", sv: "Turkiet" },
  { en: "Turkmenistan  ", sv: "Turkmenistan" },
  { en: "Tuvalu  ", sv: "Tuvalu" },
  { en: "Uganda  ", sv: "Uganda" },
  { en: "Ukraine  ", sv: "Ukraina" },
  { en: "United Arab Emirates ", sv: "Förenade Arabemiraten" },
  { en: "United Kingdom ", sv: "Storbritannien" },
  { en: "United States", sv: "USA" },
  { en: "United States", sv: "Amerikas förenta stater" },
  { en: "United States", sv: "USA" },
  { en: "Uruguay  ", sv: "Uruguay" },
  { en: "Uzbekistan  ", sv: "Uzbekistan" },
  { en: "Vanuatu  ", sv: "Vanuatu" },
  { en: "Venezuela  ", sv: "Venezuela" },
  { en: "Vietnam  ", sv: "Vietnam" },
  { en: "Yemen  ", sv: "Jemen" },
  { en: "Zambia  ", sv: "Zambia" },
  { en: "Zimbabwe  ", sv: "Zimbabwe" },
]
